name: hypnos::checks

on:
  pull_request:
    branches:
      - dev
      - dev/*
      - main
      - main/*

jobs:
  run-build:
    name: hypnos::checks::build
    runs-on: ubuntu-latest

    steps:
      - name: hypnos::checks::build::Check out Git repository
        uses: actions/checkout@v3

      - name: hypnos::checks::build::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: hypnos::checks::build::Install Node.js dependencies
        run: npm ci

      - name: hypnos::checks::build::Build
        run: npm run build
        env:
          EMAIL_SERVER: ${{ secrets.EMAIL_SERVER_PROD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM_PROD }}

  run-lint:
    name: hypnos::checks::lint
    runs-on: ubuntu-latest

    steps:
      - name: hypnos::checks::lint::Check out Git repository
        uses: actions/checkout@v3

      - name: hypnos::checks::lint::Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # ESLint and Prettier must be in `package.json`
      - name: hypnos::checks::lint::Install Node.js dependencies
        run: npm ci

      - name: hypnos::checks::lint::Run linters
        run: npm run format
